classifiers = {
"Development Status :: 1 - Planning": "in development",
"Development Status :: 2 - Pre-Alpha": "in development",
"Development Status :: 3 - Alpha": "in development",
"Development Status :: 4 - Beta": "in development",
"Development Status :: 5 - Production/Stable": "mature",
"Development Status :: 6 - Mature": "mature",
"Development Status :: 7 - Inactive": "obsolete",
"Environment :: Console": "console application",
"Environment :: Console :: Curses": "console application",
"Environment :: Console :: Framebuffer": "console application",
"Environment :: Console :: Newt": "console application",
"Environment :: Console :: svgalib": "console application",
"Environment :: Handhelds/PDA's": "mobile application",
"Environment :: MacOS X": "GUI application",
"Environment :: MacOS X :: Aqua": "GUI application",
"Environment :: MacOS X :: Carbon": "GUI application",
"Environment :: MacOS X :: Cocoa": "GUI application",
"Environment :: No Input/Output (Daemon)": "daemon application",
"Environment :: Web Environment": "web application",
"Environment :: Web Environment :: Buffet": "web application",
"Environment :: Web Environment :: Mozilla": "web application",
"Environment :: Web Environment :: ToscaWidgets": "web application",
"Environment :: Win32 (MS Windows)": "GUI application",
"Environment :: X11 Applications": "GUI application",
"Environment :: X11 Applications :: Gnome": "GUI application",
"Environment :: X11 Applications :: GTK": "GUI application",
"Environment :: X11 Applications :: KDE": "GUI application",
"Environment :: X11 Applications :: Qt": "GUI application",
"Topic :: Database": "database",
"Topic :: Database :: Database Engines/Servers": "database",
"Topic :: Database :: Front-Ends": "database",
"Topic :: Multimedia :: Graphics": "graphics",
"Topic :: Multimedia :: Graphics :: 3D Modeling": "3d modeling",
"Topic :: Multimedia :: Graphics :: 3D Rendering": "3d rendering",
"Topic :: Multimedia :: Graphics :: Capture": "graphics capture",
"Topic :: Multimedia :: Graphics :: Capture :: Digital Camera": "digital camera",
"Topic :: Multimedia :: Sound/Audio": "audio",
"Topic :: Multimedia :: Sound/Audio :: Analysis": "audio analysis",
"Topic :: Multimedia :: Sound/Audio :: Capture/Recording": "audio capture",
"Topic :: Multimedia :: Sound/Audio :: Editors": "audio editor",
"Topic :: Multimedia :: Sound/Audio :: Sound Synthesis": "sound synthesis",
"Topic :: Multimedia :: Sound/Audio :: Speech": "speech",
"Topic :: Multimedia :: Video": "video",
"Topic :: Multimedia :: Video :: Capture": "video capture",
"Topic :: Multimedia :: Video :: Non-Linear Editor": "video editor",
"Topic :: Scientific/Engineering :: Artificial Intelligence": "artificial intelligence",
"Topic :: Scientific/Engineering :: Artificial Life": "artificial life",
"Topic :: Scientific/Engineering :: Astronomy": "astronomy",
"Topic :: Scientific/Engineering :: Atmospheric Science": "atmospheric science",
"Topic :: Scientific/Engineering :: Bio-Informatics": "bio-informatics",
"Topic :: Scientific/Engineering :: Chemistry": "chemistry",
"Topic :: Scientific/Engineering :: Electronic Design Automation (EDA)": "electronic design automation",
"Topic :: Scientific/Engineering :: GIS": "GIS",
"Topic :: Scientific/Engineering :: Human Machine Interfaces": "human machine interfaces",
"Topic :: Scientific/Engineering :: Image Recognition": "image recognition",
"Topic :: Scientific/Engineering :: Information Analysis": "information analysis",
"Topic :: Scientific/Engineering :: Mathematics": "mathematics",
"Topic :: Scientific/Engineering :: Medical Science Apps.": "medical science",
"Topic :: Scientific/Engineering :: Physics": "physics",
"Topic :: Scientific/Engineering :: Visualization": "visualization",
"Topic :: Security": "security",
"Topic :: Security :: Cryptography": "cryptography",
"Topic :: Sociology": "sociology",
"Topic :: Sociology :: Genealogy": "genealogy",
"Topic :: Sociology :: History": "history",
"Topic :: Text Processing :: Indexing": "text indexing",
"Topic :: Text Processing :: Linguistic": "linguistics",
}

get = classifiers.get
